export const CORE_SERVICES = [
  {
    slug: "rapid-plumbing-fix",
    name: "Rapid Plumbing Fix",
    emojiIcon: "🔧",
    description: "On-demand pipe repairs, leak sealing, and fixture installs within 2 hours.",
    price: 49,
    category: "plumbing",
    rating: 4.9,
    bookingCount: 180,
    tags: ["emergency", "water", "bathroom"],
  },
  {
    slug: "lightning-electrical-check",
    name: "Lightning Electrical Check",
    emojiIcon: "⚡",
    description: "Certified electricians to troubleshoot short circuits and upgrade breakers.",
    price: 59,
    category: "electrical",
    rating: 4.8,
    bookingCount: 150,
    tags: ["safety", "inspection"],
  },
  {
    slug: "deep-clean-deluxe",
    name: "Deep Clean Deluxe",
    emojiIcon: "🧼",
    description: "Full-home deep cleaning with eco-friendly supplies and same-day slots.",
    price: 75,
    category: "cleaning",
    rating: 4.95,
    bookingCount: 220,
    tags: ["home", "apartment", "eco"],
  },
  {
    slug: "appliance-hero-visit",
    name: "Appliance Hero Visit",
    emojiIcon: "🧊",
    description: "Diagnose and fix refrigerators, washers, and ovens with spare parts stocked.",
    price: 65,
    category: "appliance",
    rating: 4.7,
    bookingCount: 160,
    tags: ["kitchen", "laundry"],
  },
  {
    slug: "instant-paint-refresh",
    name: "Instant Paint Refresh",
    emojiIcon: "🎨",
    description: "Accent wall refresh or touch-ups with zero-mess guarantee.",
    price: 85,
    category: "painting",
    rating: 4.6,
    bookingCount: 120,
    tags: ["renovation", "interior"],
  },
  {
    slug: "move-care-crew",
    name: "Move & Care Crew",
    emojiIcon: "📦",
    description: "Two movers with protective gear for stress-free apartment moves.",
    price: 110,
    category: "moving",
    rating: 4.8,
    bookingCount: 140,
    tags: ["logistics", "relocation"],
  },
  {
    slug: "handyman-express",
    name: "Handyman Express",
    emojiIcon: "🛠️",
    description: "Mount TVs, assemble furniture, and knock out punch-list tasks in one visit.",
    price: 55,
    category: "handyman",
    rating: 4.85,
    bookingCount: 200,
    tags: ["assembly", "repairs"],
  },
  {
    slug: "garden-tlc",
    name: "Garden TLC",
    emojiIcon: "🌿",
    description: "Seasonal trimming, lawn care, and balcony garden refresh packages.",
    price: 60,
    category: "gardening",
    rating: 4.65,
    bookingCount: 95,
    tags: ["outdoor", "plants"],
  },
  {
    slug: "smart-security-setup",
    name: "Smart Security Setup",
    emojiIcon: "🛡️",
    description: "Install and configure CCTV, smart locks, and motion sensors.",
    price: 105,
    category: "security",
    rating: 4.75,
    bookingCount: 130,
    tags: ["iot", "monitoring"],
  },
  {
    slug: "at-home-wellness",
    name: "At-Home Wellness Massage",
    emojiIcon: "💆",
    description: "Licensed therapists bring spa-grade relaxation to your living room.",
    price: 95,
    category: "wellness",
    rating: 4.9,
    bookingCount: 170,
    tags: ["relax", "health"],
  },
];

